version: '3'

services:
  postgresql:
    image: postgres:10-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: aoe
      POSTGRES_PASSWORD: wololo
      POSTGRES_USER: wololo
    ports:
      - "5445:5432"
    
